apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertmanager-config
  labels:
    resource: prometheus
spec:
  route:
    groupBy: ['severity']
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 12h
    receiver: 'email-notifications'
  receivers:
    - name: 'email-notifications'
      emailConfigs:
        - to: 'enter your first email (will be prometheus email)'
          from: 'enter the target email (prometheus will sent alerts to this email from the previous email)'
          smarthost: 'smtp.gmail.com:587'
          authUsername: 'first email'
          authIdentity: 'first email'
          authPassword:
            name: gmail-auth
            key: password
